import numpy as np
# print(np.__version__)
ar=np.array([1,2,3,4,5])
# print(arr)
# print(type(arr))
# c= np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
# print(c)
# print(c.shape)
# print(c.size)
# print(c.ndim)
# print(c.dtype)

# a=np.zeros((2,3))
# print(a)
# o=np.ones((2,2))
# print(o)
# c=np.arange(0,10,2)
# print(c)
# d=np.linspace(0,1,5)
# print(d)

# e=np.eye(3)
# print(e)

# print(np.random.random((2,3)))
# print(np.random.randint(1,10,(2,3)))
# print(arr[2])

a=np.array([[1,2],[4,5]])
c=np.array([[7,2],[4,7]])
# print(a[1,2])
# print(a[0,:])
# print(a[:,1])
# print(a[a>2])
# print(arr[[0,2,4]])
# print(a[[0,1],[0,1]])

b=np.array([6,7,8,9,10])
# print(arr+b)
# print(arr-b)
# print(arr*b)
# print(arr/b)

# print(arr+a)
# print(np.sum(a))
# print(np.mean(a))
# print(np.median(a))
# print(np.std(a))
# print(np.var(a))
# print(np.min(a))
# print(np.max(a))
# print(np.argmin(a))
# print(np.argmax(a))
# new=a.reshape(3,2)
# print(new)
# print(a.flatten())
# print(a.ravel())
# print(a.transpose())
# print(np.concatenate((arr,b)))
# print(np.split(arr,2))
# r=np.matmul(a,c)
# print(r)
# print(np.dot(ar,b))
# print(np.linalg.inv(a))
# print(np.linalg.det(a))
# print(np.linalg.eig(a))
print(np.random.rand(3))
h=[1,2,3,4]
print(np.random.choice(h,3))
print(np.random.normal(loc=0,scale=1,size=5))
t=np.random.default_rng(seed=10)

print(t.random())

